extern "C" void exit(int);

extern "C" void RTExceptions_DefaultErrorCatch(void);
extern "C" void _M2_Storage_init (int argc, char *argv[]);
extern "C" void _M2_Storage_finish (void);
extern "C" void _M2_SYSTEM_init (int argc, char *argv[]);
extern "C" void _M2_SYSTEM_finish (void);
extern "C" void _M2_M2RTS_init (int argc, char *argv[]);
extern "C" void _M2_M2RTS_finish (void);
extern "C" void _M2_RTExceptions_init (int argc, char *argv[]);
extern "C" void _M2_RTExceptions_finish (void);
extern "C" void _M2_Indexing_init (int argc, char *argv[]);
extern "C" void _M2_Indexing_finish (void);
extern "C" void _M2_NumberIO_init (int argc, char *argv[]);
extern "C" void _M2_NumberIO_finish (void);
extern "C" void _M2_StrLib_init (int argc, char *argv[]);
extern "C" void _M2_StrLib_finish (void);
extern "C" void _M2_FIO_init (int argc, char *argv[]);
extern "C" void _M2_FIO_finish (void);
extern "C" void _M2_errno_init (int argc, char *argv[]);
extern "C" void _M2_errno_finish (void);
extern "C" void _M2_termios_init (int argc, char *argv[]);
extern "C" void _M2_termios_finish (void);
extern "C" void _M2_IO_init (int argc, char *argv[]);
extern "C" void _M2_IO_finish (void);
extern "C" void _M2_Debug_init (int argc, char *argv[]);
extern "C" void _M2_Debug_finish (void);
extern "C" void _M2_StdIO_init (int argc, char *argv[]);
extern "C" void _M2_StdIO_finish (void);
extern "C" void _M2_SysStorage_init (int argc, char *argv[]);
extern "C" void _M2_SysStorage_finish (void);
extern "C" void _M2_SysExceptions_init (int argc, char *argv[]);
extern "C" void _M2_SysExceptions_finish (void);
extern "C" void _M2_M2EXCEPTION_init (int argc, char *argv[]);
extern "C" void _M2_M2EXCEPTION_finish (void);
extern "C" void _M2_StrIO_init (int argc, char *argv[]);
extern "C" void _M2_StrIO_finish (void);
extern "C" void _M2_ASCII_init (int argc, char *argv[]);
extern "C" void _M2_ASCII_finish (void);
extern "C" void _M2_Display_init (int argc, char *argv[]);
extern "C" void _M2_Display_finish (void);
extern "C" void _M2_Keyboard_init (int argc, char *argv[]);
extern "C" void _M2_Keyboard_finish (void);
extern "C" void _M2_ConvTypes_init (int argc, char *argv[]);
extern "C" void _M2_ConvTypes_finish (void);
extern "C" void _M2_Assertion_init (int argc, char *argv[]);
extern "C" void _M2_Assertion_finish (void);
extern "C" void _M2_CharClass_init (int argc, char *argv[]);
extern "C" void _M2_CharClass_finish (void);
extern "C" void _M2_EXCEPTIONS_init (int argc, char *argv[]);
extern "C" void _M2_EXCEPTIONS_finish (void);
extern "C" void _M2_ldtoa_init (int argc, char *argv[]);
extern "C" void _M2_ldtoa_finish (void);
extern "C" void _M2_dtoa_init (int argc, char *argv[]);
extern "C" void _M2_dtoa_finish (void);
extern "C" void _M2_WholeConv_init (int argc, char *argv[]);
extern "C" void _M2_WholeConv_finish (void);
extern "C" void _M2_Termbase_init (int argc, char *argv[]);
extern "C" void _M2_Termbase_finish (void);
extern "C" void _M2_StringConvert_init (int argc, char *argv[]);
extern "C" void _M2_StringConvert_finish (void);
extern "C" void _M2_wrapc_init (int argc, char *argv[]);
extern "C" void _M2_wrapc_finish (void);
extern "C" void _M2_FormatStrings_init (int argc, char *argv[]);
extern "C" void _M2_FormatStrings_finish (void);
extern "C" void _M2_DynamicStrings_init (int argc, char *argv[]);
extern "C" void _M2_DynamicStrings_finish (void);
extern "C" void _M2_SFIO_init (int argc, char *argv[]);
extern "C" void _M2_SFIO_finish (void);
extern "C" void _M2_Terminal_init (int argc, char *argv[]);
extern "C" void _M2_Terminal_finish (void);
extern "C" void _M2_Strings_init (int argc, char *argv[]);
extern "C" void _M2_Strings_finish (void);
extern "C" void _M2_Selective_init (int argc, char *argv[]);
extern "C" void _M2_Selective_finish (void);
extern "C" void _M2_FpuIO_init (int argc, char *argv[]);
extern "C" void _M2_FpuIO_finish (void);
extern "C" void _M2_WholeStr_init (int argc, char *argv[]);
extern "C" void _M2_WholeStr_finish (void);
extern "C" void _M2_FileSystem_init (int argc, char *argv[]);
extern "C" void _M2_FileSystem_finish (void);
extern "C" void _M2_Delay_init (int argc, char *argv[]);
extern "C" void _M2_Delay_finish (void);
extern "C" void _M2_MathLib0_init (int argc, char *argv[]);
extern "C" void _M2_MathLib0_finish (void);
extern "C" void _M2_PulseLib_init (int argc, char *argv[]);
extern "C" void _M2_PulseLib_finish (void);
extern "C" void _M2_GradientLib_init (int argc, char *argv[]);
extern "C" void _M2_GradientLib_finish (void);
extern "C" void _M2_MatrixMathLib_init (int argc, char *argv[]);
extern "C" void _M2_MatrixMathLib_finish (void);
extern "C" void _M2_SpinOperatorLib_init (int argc, char *argv[]);
extern "C" void _M2_SpinOperatorLib_finish (void);
extern "C" void _M2_BinaryFilesInOut_init (int argc, char *argv[]);
extern "C" void _M2_BinaryFilesInOut_finish (void);
extern "C" void _M2_Fourier_init (int argc, char *argv[]);
extern "C" void _M2_Fourier_finish (void);
extern "C" void _M2_DataFilesInout_init (int argc, char *argv[]);
extern "C" void _M2_DataFilesInout_finish (void);
extern "C" void _M2_RealInOut_init (int argc, char *argv[]);
extern "C" void _M2_RealInOut_finish (void);
extern "C" void _M2_InOut_init (int argc, char *argv[]);
extern "C" void _M2_InOut_finish (void);
extern "C" void _M2_TimeDate_init (int argc, char *argv[]);
extern "C" void _M2_TimeDate_finish (void);
extern "C" void _M2_PulseSequence_init (int argc, char *argv[]);
extern "C" void _M2_PulseSequence_finish (void);
extern "C" void _M2_DebugPMD_init (int argc, char *argv[]);
extern "C" void _M2_DebugPMD_finish (void);
extern "C" void _M2_CalculateSpectra_init (int argc, char *argv[]);
extern "C" void _M2_CalculateSpectra_finish (void);
extern "C" void _M2_ilv_init (int argc, char *argv[]);
extern "C" void _M2_ilv_finish (void);

extern "C" void M2RTS_ExecuteTerminationProcedures(void);

extern "C" void M2RTS_ExecuteInitialProcedures(void);

static void init (int argc, char *argv[])
{
   try {
       _M2_Storage_init (argc, argv);
       _M2_SYSTEM_init (argc, argv);
       _M2_M2RTS_init (argc, argv);
       _M2_RTExceptions_init (argc, argv);
       _M2_Indexing_init (argc, argv);
       _M2_NumberIO_init (argc, argv);
       _M2_StrLib_init (argc, argv);
       _M2_FIO_init (argc, argv);
       _M2_errno_init (argc, argv);
       _M2_termios_init (argc, argv);
       _M2_IO_init (argc, argv);
       _M2_Debug_init (argc, argv);
       _M2_StdIO_init (argc, argv);
       _M2_SysStorage_init (argc, argv);
       _M2_SysExceptions_init (argc, argv);
       _M2_M2EXCEPTION_init (argc, argv);
       _M2_StrIO_init (argc, argv);
       _M2_ASCII_init (argc, argv);
       _M2_Display_init (argc, argv);
       _M2_Keyboard_init (argc, argv);
       _M2_ConvTypes_init (argc, argv);
       _M2_Assertion_init (argc, argv);
       _M2_CharClass_init (argc, argv);
       _M2_EXCEPTIONS_init (argc, argv);
       _M2_ldtoa_init (argc, argv);
       _M2_dtoa_init (argc, argv);
       _M2_WholeConv_init (argc, argv);
       _M2_Termbase_init (argc, argv);
       _M2_StringConvert_init (argc, argv);
       _M2_wrapc_init (argc, argv);
       _M2_FormatStrings_init (argc, argv);
       _M2_DynamicStrings_init (argc, argv);
       _M2_SFIO_init (argc, argv);
       _M2_Terminal_init (argc, argv);
       _M2_Strings_init (argc, argv);
       _M2_Selective_init (argc, argv);
       _M2_FpuIO_init (argc, argv);
       _M2_WholeStr_init (argc, argv);
       _M2_FileSystem_init (argc, argv);
       _M2_Delay_init (argc, argv);
       _M2_MathLib0_init (argc, argv);
       _M2_PulseLib_init (argc, argv);
       _M2_GradientLib_init (argc, argv);
       _M2_MatrixMathLib_init (argc, argv);
       _M2_SpinOperatorLib_init (argc, argv);
       _M2_BinaryFilesInOut_init (argc, argv);
       _M2_Fourier_init (argc, argv);
       _M2_DataFilesInout_init (argc, argv);
       _M2_RealInOut_init (argc, argv);
       _M2_InOut_init (argc, argv);
       _M2_TimeDate_init (argc, argv);
       _M2_PulseSequence_init (argc, argv);
       _M2_DebugPMD_init (argc, argv);
       _M2_CalculateSpectra_init (argc, argv);
      M2RTS_ExecuteInitialProcedures ();
       _M2_ilv_init (argc, argv);
    }
    catch (...) {
       RTExceptions_DefaultErrorCatch();
    }
}

static void finish (void)
{
   try {
      M2RTS_ExecuteTerminationProcedures ();
      _M2_ilv_finish ();
      _M2_CalculateSpectra_finish ();
      _M2_DebugPMD_finish ();
      _M2_PulseSequence_finish ();
      _M2_TimeDate_finish ();
      _M2_InOut_finish ();
      _M2_RealInOut_finish ();
      _M2_DataFilesInout_finish ();
      _M2_Fourier_finish ();
      _M2_BinaryFilesInOut_finish ();
      _M2_SpinOperatorLib_finish ();
      _M2_MatrixMathLib_finish ();
      _M2_GradientLib_finish ();
      _M2_PulseLib_finish ();
      _M2_MathLib0_finish ();
      _M2_Delay_finish ();
      _M2_FileSystem_finish ();
      _M2_WholeStr_finish ();
      _M2_FpuIO_finish ();
      _M2_Selective_finish ();
      _M2_Strings_finish ();
      _M2_Terminal_finish ();
      _M2_SFIO_finish ();
      _M2_DynamicStrings_finish ();
      _M2_FormatStrings_finish ();
      _M2_wrapc_finish ();
      _M2_StringConvert_finish ();
      _M2_Termbase_finish ();
      _M2_WholeConv_finish ();
      _M2_dtoa_finish ();
      _M2_ldtoa_finish ();
      _M2_EXCEPTIONS_finish ();
      _M2_CharClass_finish ();
      _M2_Assertion_finish ();
      _M2_ConvTypes_finish ();
      _M2_Keyboard_finish ();
      _M2_Display_finish ();
      _M2_ASCII_finish ();
      _M2_StrIO_finish ();
      _M2_M2EXCEPTION_finish ();
      _M2_SysExceptions_finish ();
      _M2_SysStorage_finish ();
      _M2_StdIO_finish ();
      _M2_Debug_finish ();
      _M2_IO_finish ();
      _M2_termios_finish ();
      _M2_errno_finish ();
      _M2_FIO_finish ();
      _M2_StrLib_finish ();
      _M2_NumberIO_finish ();
      _M2_Indexing_finish ();
      _M2_RTExceptions_finish ();
      _M2_M2RTS_finish ();
      _M2_SYSTEM_finish ();
      _M2_Storage_finish ();
      exit (0);
    }
    catch (...) {
       RTExceptions_DefaultErrorCatch();
    }
}

int main (int argc, char *argv[])
{
   init (argc, argv);
   finish ();
   return (0);
}
